[build-system]
requires = ["setuptools>=67.6.1"]
build-backend = "setuptools.build_meta"

[project]
name = "nimocr"
version = "0.0.1"
description = "An MUOCR packages for text recognizer."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "numpy==1.24.2",
    "opencv_python==4.7.0.72",
    "pandas==2.0.0",
    "Pillow==9.5.0",
    "PyQt6==6.5.0",
]
